### ISSUE TITLE
only returning email

### ISSUE THREAD

**Issue by roychowdhurysourav23** [ionicthemes/google-login-ionic-framework#1]
Hello,

while calling window.plugins.googleplus.login() function.its only returning email.how to get all user data,where i am doing wrong.please suggest

**Comment by roychowdhurysourav23** [comment]
Waiting for a reply.

**Comment by alexbonhomme** [comment]
+1 I get exactly the same issue...

**Comment by djabif** [comment]
Please check https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/146 to find how to fix this.
