### ISSUE TITLE
user cant login when press login button

### ISSUE THREAD

**Issue by babitabhandari** [ionicthemes/google-login-ionic-framework#3]
I have follow this tutorial https://ionicthemes.com/tutorials/about/google-plus-login-with-ionic-framework
but i have an issue that when i click sign in with google button its sign in is loading but does not go to user profile and error occurs.
(https://cloud.githubusercontent.com/assets/8756834/13275928/35264a9e-dae0-11e5-9146-4f5ff56dfabd.png)

**Comment by djabif** [comment]
This is because you are testing this in the browser. Google plugin only works on a real device or emulator.
